### ISSUE TITLE
Where is the router?

### ISSUE THREAD

**Issue by ecojuntak** [kEpEx/laravel-crud-generator#10]
Hi, I just trying use your package, is so cool.

But, I confuse where the router? for example, when I wanna access <test>/create, but the <test>/create not register in my router. 

Explain me, please,
Thank you

**Comment by kEpEx** [comment]
Hey, sorry for the late response, basically the generator add a generic controller route, so we dont need to specify individual routes for every method, you can use naming convention for the methods in the controller, so if you want to customize those names, you just need to change the name of the method, I hope i was clear. 

See implicit controllers in the laravel documentation:

https://laravel.com/docs/5.1/controllers#implicit-controllers
