### ISSUE TITLE
Ajax not work

### ISSUE THREAD

**Issue by qeifar** [kEpEx/laravel-crud-generator#11]
Theres nothing showed on the list

**Comment by SamyOteroGlez** [comment]
Hi @qeifar.

Are you receiving any console error?
I would check for console errors in the browser.

Cheers.

**Comment by qeifar** [comment]
It work awesomely right now.. It occurs because I have two tables use singular and plural name like 'role' and 'roles'. The others work fine... But can I change the directory for the model, view and controller to be located ? 👍

**Comment by SamyOteroGlez** [comment]
@qeifar 
I am sure you can, but remember to change it every where.

Cheers
