### ISSUE TITLE
Directory Changing

### ISSUE THREAD

**Issue by qeifar** [kEpEx/laravel-crud-generator#12]
Let's says I need to generate the Model in App/Models folder.. not in App/ folder..  Which code I should change? This?
https://github.com/kEpEx/laravel-crud-generator/blob/master/src/CrudGeneratorService.php

**Comment by SamyOteroGlez** [comment]
@qeifar 

All the model creation logic happens in `createModel()`. I would start looking there.

Cheers

**Comment by qeifar** [comment]
The controller and view successfully transfered to my required directory but not for the model: when I changed https://github.com/kEpEx/laravel-crud-generator/blob/master/src/CrudGeneratorService.php

On the url part.. Did I need to adjust other file too?

**Comment by qeifar** [comment]
just edit "Artisan:call" instead. from make model User.. to make model Models/User.. 💯
Thanks everyone!
