### ISSUE TITLE
Undefined variable model in add.blade.php view

### ISSUE THREAD

**Issue by ch-kashif171** [kEpEx/laravel-crud-generator#18]
I am facing an issue that when i clicked on add button for open the add form then error occurred that says
Undefined variable model in add.blade.php view.
I think there is need to set "isset" condition.

**Comment by rayan-appzod** [comment]
Hello
just do this :
php artisan vendor:publish
then go to  C:\xampp\htdocs\your_project\resources\templates
you will find file view.add.tpl.php
edit it and replace with this and you will get problem solved
[view.add.tpl.php.zip](https://github.com/kEpEx/laravel-crud-generator/files/3168241/view.add.tpl.php.zip)

**Comment by DanielQuirogaDev** [comment]
Thank you, quickest fix ever.

**Comment by ch-kashif171** [comment]
Thank you.
