### ISSUE TITLE
Runtime Exception while running "php artisan make:crud State table-name=states"

### ISSUE THREAD

**Issue by maheshtc** [kEpEx/laravel-crud-generator#2]
I am using your extension and while executing following command I am getting
**php artisan make:crud State table-name=states**
[RuntimeException]  
Too many arguments.

What could be the issue for this runtime exception.

**Comment by maheshtc** [comment]
Sorry It was my mistake. I have forgotten to add **--table-name**.

**Comment by kEpEx** [comment]
NP, glad I can help :)
