### ISSUE TITLE
not able to create crud for single table in Laravel 5

### ISSUE THREAD

**Issue by nullcall** [kEpEx/laravel-crud-generator#5]
D:\master>php artisan make:crud **_product_serice_**

Creating catalog for table: _product_serice_**s**
Model Name: Product_serice

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssc_dev.product_
  serices' doesn't exist (SQL: show columns from Product_serice**s**)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssc_dev.product_
  serice**s**' doesn't exist

==== **It's add extra 's'  at the end of table name**, due to this table not found in DB

===  MORE CLEAR ============
D:\master>php artisan make:crud **product_series2**

Creating catalogue for table: _product_series2_**s**
Model Name: Product_series2

  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssc_dev.product_
  series2s' doesn't exist (SQL: show columns from **Product_series2s**)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ssc_dev.product_
#   series2s' doesn't exist

php artisan make:crud all (is working fine)

i have php 7, mysql, apache 2.4 windows 7 64-bit. Kindly help me in this. or tell me how can i skill existing CRUD controller  instance -fore overwrite.

**Comment by ghost** [comment]
you can use the --table-name=[...] option

**Comment by kEpEx** [comment]
The naming convention for the table is the same as Eloquent uses, plural for tables, singular for models. As @pfalsoncup  says, you can specify a custom name for the table with --table-name=[...] option. 

There is one more thing, I haven't tested it using schemas... so I'm not sure if will work even with custom table name. You can try, and I can spend some time making this work probably, but it would take me a week or so...

I hope it helps!.

**Comment by nullcall** [comment]
Tx buddy.
