### ISSUE TITLE
Assumes "App" as the application name

### ISSUE THREAD

**Issue by ghost** [kEpEx/laravel-crud-generator#6]
If you rename the app to something else the resulting controller has the wrong namespace.

Suggest using Illuminate\Console\AppNamespaceDetectorTrait->getAppNamespace() instead of hard coding App.

**Comment by kEpEx** [comment]
Thanks for the tip peter, it was on my plans, I will try to implement it soon

**Comment by kEpEx** [comment]
Fixed on v0.1.6
